name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-project:
    runs-on: self-hosted

    steps:
      - name: checkout changes
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build Pactus Bot
        run: docker build --no-cache -t pactus-bot:main .


  deploy-project:
    needs: 'build-project'
    runs-on: self-hosted

    steps:
      - name: Recreate Pactus Bot with new image
        run: docker compose -f ${{ secrets.COMPOSE_PATH }} up -d

      - name: Pactus Bot status
        run: docker compose -f ${{ secrets.COMPOSE_PATH }} ps
